---
- name: Reboot Linux Servers
  hosts: servers
  become: yes             # Required to run the reboot command
  gather_facts: no        # Optional: Set to 'no' to skip the error you had earlier

  tasks:
    - name: Unconditionally reboot the machine
      ansible.builtin.reboot:
        reboot_timeout: 3600    # Wait up to 1 hour for the server to return
        post_reboot_delay: 30   # Wait 30 seconds after it's back before finishing
        test_command: whoami    # Run this to confirm the system is ready
